name: Merge

on:
  push:
    branches: [main]
    paths:
      - 'oobabooga/**'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ftechmax/runpod-oobabooga
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '6.x'
          includePrerelease: true

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Build image
        run: docker build --tag $IMAGE_NAME ./oobabooga/

      - name: Tag and push image
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:${{ steps.gitversion.outputs.semVer }}
          docker push $IMAGE_NAME:${{ steps.gitversion.outputs.semVer }}
          docker push $IMAGE_NAME:latest

      - name: Docker logout
        run: docker logout
